### ISSUE TITLE
Devfile 2.2.x support

### ISSUE THREAD

**Issue by michael-valdron** [redhat-developer/alizer#159]
/kind enhancement 

## Which area this feature is related to?

/area api
/area library

## Issue details

With the release of devfile 2.2.0, the devfile spec brings a fair amount of new features, such as outerloop and multi version support. With this in mind, it is important to the consumers of alizer to have support for `2.2.x` schema versions.

## Related Issues

UPDATE: @thepetk 
As this is transformed in an EPIC I'm including all children issues here:

- [x] https://github.com/redhat-developer/alizer/issues/225
- [x] https://github.com/redhat-developer/alizer/issues/226
- [x] https://github.com/redhat-developer/alizer/issues/227

**Comment by thepetk** [comment]
For this case, we can:

* Include an extra field in alizer response (`version`) which will include the version of the devfile.
* Make the selection process configurable and if someone passes a version alizer should detect devfiles from this version or older.
WDYT?

**Comment by thepetk** [comment]
UPDATE: We are still working on a proposal for this feature.

**Comment by thepetk** [comment]
The final refinements of the proposal are about to be done and a proper PR will be added

**Comment by thepetk** [comment]
Still working on the proposal, expecting to have a PR ready until 2nd of June. I've updated the target date

**Comment by thepetk** [comment]
I've added all related tasks to this epic

**Comment by thepetk** [comment]
closing in favor of https://github.com/devfile/api/issues/1170
