### ISSUE TITLE
Onboard Alizer

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/alizer#166]
Capture activity to onboard Alizer including addressing serviceability, Logging, build system, test automation, release process, code comment, license (EPL->Apache?), etc.

[Remove Deprecated Implementations]
- [x] https://github.com/redhat-developer/alizer/issues/172
- [x] https://github.com/redhat-developer/alizer/issues/173
- [x] https://github.com/redhat-developer/alizer/issues/185
- [x] #215 

[Update documentation, tests and build processes]
- [x] https://github.com/redhat-developer/alizer/issues/176
- [x] https://github.com/redhat-developer/alizer/issues/153 
- [x] https://github.com/redhat-developer/alizer/issues/154 
- [x] https://github.com/redhat-developer/alizer/issues/155 
- [x] https://github.com/redhat-developer/alizer/issues/151
- [x] https://github.com/redhat-developer/alizer/issues/186

[Improve functionality]
- [x] https://github.com/redhat-developer/alizer/issues/225
- [x] https://github.com/redhat-developer/alizer/issues/152
- [x] https://github.com/redhat-developer/alizer/issues/146

[Migrate Project]
- [x] https://github.com/redhat-developer/alizer/issues/240

**Comment by thepetk** [comment]
I'd say the following issues could part of this epic too :)

* https://github.com/redhat-developer/alizer/issues/159
* https://github.com/redhat-developer/alizer/issues/152
* https://github.com/redhat-developer/alizer/issues/146

**Comment by mike-hoang** [comment]
- [ ] https://github.com/redhat-developer/alizer/issues/172
- [ ] https://github.com/redhat-developer/alizer/issues/173

**Comment by thepetk** [comment]
This one I'd say too:

[] https://github.com/redhat-developer/alizer/issues/182

**Comment by elsony** [comment]
Other things that can be considered to be added as part of this Epic (feel free to cross out if they are already done):
1. Improve code comments
2. License change from EPL->Apache to align with the devfile project
3. Set up the build system for proper release build
4. Define the communication channels of the project
5. Review existing documentation: identify the gaps and create items to track
6. Set up proper PR test
7. Set up nightly test run that consumes entries in the community devfile registry and product registry - I am ok to move it out to a separate item if we want to reduce the scope of this item

**Comment by thepetk** [comment]
@elsony , @jasperchui and @mike-hoang I've created/updated all issues.
Re 1: I've updated the #154 to include this action too.
Re 2: We have already created #176 but it wasn't included in this epic. I think this should be done after the onboarding to the new organization (same as #180 for dependabot).
Re 3: Created https://github.com/redhat-developer/alizer/issues/186
Re 4: As a part of devfiles team, shouldn't have the same channels?
Re 5: The documentation has been updated with #151 , #149 and we also have the #185
Re 6: For PR testing, we have opened https://github.com/redhat-developer/alizer/issues/173 in order to remove all unnecessary checks. We are aiming to keep only the go tests. IMO they are sufficient as we have unit tests for language, devfile, component recognition (additional cases for ports) and e2e tests with the `git_test` tests.
Re 7: Created https://github.com/redhat-developer/alizer/issues/187 (I'd say it can be one of the first issues after the onboarding to devfiles)

After this input the updated list of issues should be:

[Remove Deprecated Implementations]
- [ ] https://github.com/redhat-developer/alizer/issues/172
- [ ] https://github.com/redhat-developer/alizer/issues/173
- [ ] https://github.com/redhat-developer/alizer/issues/177
- [ ] https://github.com/redhat-developer/alizer/issues/185

[Update documentation, tests and build processes]
- [ ] https://github.com/redhat-developer/alizer/issues/153 
- [ ] https://github.com/redhat-developer/alizer/issues/154 
- [ ] https://github.com/redhat-developer/alizer/issues/155 
- [x] https://github.com/redhat-developer/alizer/issues/151
- [ ] https://github.com/redhat-developer/alizer/issues/186

[Improve functionality]
- [ ] https://github.com/redhat-developer/alizer/issues/159
- [x] https://github.com/redhat-developer/alizer/issues/152
- [ ] https://github.com/redhat-developer/alizer/issues/146

WDYT?

**Comment by jasperchui** [comment]
Re 2: We have already created https://github.com/redhat-developer/alizer/issues/176 but it wasn't included in this epic. I think this should be done after the onboarding to the new organization (same as https://github.com/redhat-developer/alizer/issues/180 for dependabot).
We should complete this in this EPIC.

**Comment by elsony** [comment]
Thanks for the updates. The rest looks ok and I only have extra comments for two of them:
4: I am fine with using the devfile communication channel. Having said that, people who finds to the Alizer project currently won't know who and where to contact. We need to have it mentioned somewhere.
6: Do we have test cases for all types of applications that we intended to support? What is the current code coverage?

**Comment by thepetk** [comment]
@elsony 

> 4: I am fine with using the devfile communication channel. Having said that, people who finds to the Alizer project currently won't know who and where to contact. We need to have it mentioned somewhere.

Maybe I have misinterpreted the issue. I mean that after the onboarding, we can have the same channels as the devfiles. Before that, I'd propose that we can create a dedicated internal channel for this issue (e.g forum-alizer) and for the outerloop I'd say we can continue relying on the github issues. So, any person who want to communicate about alizer they would have to create an issue.

> 6: Do we have test cases for all types of applications that we intended to support? What is the current code coverage?

I've created the [coverage.csv](https://github.com/redhat-developer/alizer/files/11304487/coverage.csv) which lists all paths/functions that **don't have** coverage 100%. **The average coverage is: 78.60%**.

In order to improve this number I've created the https://github.com/redhat-developer/alizer/issues/194 with all cases that are missing from `component` (and port) & `devfile` detection.

**Comment by michael-valdron** [comment]
Could we update the acceptance criteria for this epic to include the additional child issues mentioned in the story?

cc: @thepetk @mike-hoang

**Comment by thepetk** [comment]
Yes I'll do that soon :)

**Comment by thepetk** [comment]
I've updated the list of tasks remaining for the onboarding

**Comment by thepetk** [comment]
I've updated the acceptance criteria for the EPIC. I've removed https://github.com/redhat-developer/alizer/issues/226 from the list as it is blocked and the onboarding can be done even if is not completed

**Comment by thepetk** [comment]
Some details about the final list:

* #159 Has been transformed into an epic and removed from the final list. The blocking part for this EPIC is done (#225 and #153 )
* #177 Was split into two steps ( the part related with onboarding is https://github.com/redhat-developer/alizer/issues/240)
