### ISSUE TITLE
Migrate Alizer to Devfiles organization

### ISSUE THREAD

**Issue by mike-hoang** [redhat-developer/alizer#240]
## Which area/kind this issue is related to?

/kind epic
/area releng

## Issue Description

Migrate Alizer from redhat-developer to the [devfile organization](https://github.com/devfile).

Create a new repo `devfile/alizer` with a clone of `redhat-developer/alizer`, which is then marked as deprecated. Users then have to manually switch to the new import path when they want to upgrade to the non deprecated version.

Related: Post onboarding actions https://github.com/redhat-developer/alizer/issues/239

## Acceptance Criteria

- [x] Create `devfile/alizer` with a clone of `redhat-developer/alizer`
- [x] https://github.com/redhat-developer/alizer/issues/177
- [x] https://github.com/devfile/api/issues/1148
- [x] Add a notice to readme - https://github.com/redhat-developer/alizer/pull/255
- [ ] Archive `redhat-developer/alizer`

**Comment by mike-hoang** [comment]
Two approaches for the migration from Alizer to Devfiles:

## Approach 1 - GitHub "Transfer ownership"

Using the Transfer option in the repo settings, GitHub will automatically redirect all traffic from `https://github.com/redhat-developer/alizer` to `https://github.com/devfile/alizer`.

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

Pros

+ Quickest / least amount of work for users
+ Transfers all history: issues, prs, starts, watchers, contributions, web hooks, secrets, deploy keys

Cons

- Renaming the `go.mod` module name will still result in users needing to change their `go.mod` (i.e. if we want to flatten the repo structure)

```
➜  test-alizer git:(main) ✗ go get github.com/mike-hoang/alizer-copy/go@09ec9e5
go: downloading github.com/mike-hoang/alizer-copy v0.0.0-20230626152052-09ec9e515baf
go: downloading github.com/mike-hoang/alizer-copy/go v0.0.0-20230626152052-09ec9e515baf
go: github.com/mike-hoang/alizer-copy/go@v0.0.0-20230626152052-09ec9e515baf: parsing go.mod:
        module declares its path as: github.com/thepetk/alizer-copy/go
                but was required as: github.com/mike-hoang/alizer-copy/go
``` 

## Approach 2 - Duplicate Alizer

Create a new repo `devfile/alizer` with a clone of `redhat-developer/alizer`, which is then marked as deprecated. Users then have to manually switch to the new import path when they want to upgrade to the non deprecated version.


Pros

+ Allows for major changes without breaking existing users; repo structure can be flattened (changing `module github.com/redhat-developer/alizer/go` to `module github.com/devfile/alizer`)

Cons

- Will lose all history
- Will need to recreate all issues
- Extra work for users

**Comment by michael-valdron** [comment]
I'm leaning towards *Approach 2 - Duplicate Alizer* because it will allow us to preserve the old imports for the users preventing things from breaking as well as allow us to do the refactoring changes in the new location.

Two things that concern me a bit about this approach but perhaps is workable:
1. Spotty migration of item history, particularly issues and PRs
    - Could be doable through tools and linking old items to the new ones
3. Ensuring users switch to `devfile/alizer` for further changes
    - We should public archive `red-developer/alizer` if  we choose this approach

**Comment by thepetk** [comment]
I'd say too approach 2. If we follow this approach the current issue should be transformed to an EPIC. Actions regarding the epic could be

* We can create a new repo and import existing alizer's code.
* Complete #177 and merge to the devfile (new) repo.
* Migrate all open issues to new repo. We could also move the closed issues by just having a link to the archived version.

**Comment by michael-valdron** [comment]
> Migrate all open issues to new repo. We could also move the closed issues by just having a link to the archived version.

I am preferring the reverse, having a link to the active issue in the archived ones, but any linkage is good.

**Comment by mike-hoang** [comment]
@elsony @thepetk If we decide on approach two, I can convert this to an epic and create the new Alizer repo in the Devfile org

**Comment by elsony** [comment]
+1 on approach #2 to allow users to migrate at their own pace. Given that we are still preserving the old repo as a deprecated/archived repo, we, strictly speaking, still have the old history. We can still find the history from the archived repo if we need to. I think it is a good trade-off compared to requiring users to migrate to avoid breakage.

**Comment by thepetk** [comment]
I've created a list of tasks regarding the migration to devfiles here: https://github.com/devfile/api/issues/1148
I think we need to move all issues to devfile/api as this is the way that the devfile org works. We should also update documentation for sprint boss, issue templates and our agenda docs.

**Comment by thepetk** [comment]
I've created a final release `v0.3.0` for old alizer repo. No updates should be made (except documentation ofc) to this repo from now on :)
