### ISSUE TITLE
Support devfiles port/component detection and default ports

### ISSUE THREAD

**Issue by thepetk** [redhat-developer/alizer#245]
## Which area this feature is related to?

/area api
/area library
/area test-automation
/area documentation

## Which functionality do you think we should add?
A good addition to our current port/component detection logic would be to recognize devfile components and ports.

As a result, we will have a clearer image for port detection and for specific frameworks we could now return `default_ports` in case they are not configured inside the given application code (devfile, docker, docker-compose and source code).

Default ports feature has been discussed also in several issues in the past like #146 and #212.

**Why is this needed? Is your feature request related to a problem?**

This will be a good improvement in Alizer's component and port detection logic and will make Alizer more accurate in its analysis.

## Describe the solution you'd like

This feature demands a fair amount of updates to the logic of Alizer. That's why it is created as an epic and a proposal should be created.

As a high overview of the solution:

* We need to implement a devfile component and port detection logic first. This will ensure that no port is configured inside the code and then we can include default ports to Alizer's response.
* In each framework detector we should list all default ports. Also upon port detection if no port is detected we should return the default port (if any) for this framework.
* An addition to our CLI params for `component` analysis we will need to add one more for `default_ports`. This way we allow the users to choose if they want default ports to be included or not.

## Acceptance Criteria
As acceptance criteria for this EPIC the following issues must be completed:

- [ ] https://github.com/redhat-developer/alizer/issues/246
- [ ] https://github.com/redhat-developer/alizer/issues/247
- [ ] https://github.com/redhat-developer/alizer/issues/248
- [ ] https://github.com/redhat-developer/alizer/issues/249

**Comment by thepetk** [comment]
closing in favor of https://github.com/devfile/api/issues/1154
